homepage:
    path: /
    controller: App\Controller\HomeController::index

########################################
############# RUTAS EVENTOS ############

# Ruta para la API de eventos (JSON response)
api_events:
    path: /api/events
    controller: App\Controller\AdminEventController::listEventsApi
    methods: [GET]

# Ruta para la creación de eventos desde el backend 
admin_create_event:
    path: /admin/events/new
    controller: App\Controller\AdminEventController::createEvent
    methods: [GET, POST]

# Ruta para editar un evento
admin_edit_event:
    path: /admin/events/edit/{id}
    controller: App\Controller\AdminEventController::editEvent
    methods: [GET, POST]

# Ruta para ver los detalles de un evento específico
event_detail:
    path: /events/{id}
    controller: App\Controller\AdminEventController::showEvent
    methods: [GET]

# Ruta para listar eventos desde el backend (renderiza Twig, no JSON)
event_list:
    path: /events
    controller: App\Controller\AdminEventController::listEvents
    methods: [GET]

# Ruta para eliminar un evento
event_delete:
    path: /admin/events/delete/{id}
    controller: App\Controller\AdminEventController::deleteEvent
    methods: [POST]

# Ruta para mostrar el formulario de creación de un nuevo evento
admin_create_event_form:
    path: /admin/events/new
    controller: App\Controller\AdminEventController::createEventForm
    methods: [GET]

# Ruta para la creación de un nuevo evento a través de la API
admin_create_event_api:
    path: /api/admin/events/new
    controller: App\Controller\AdminEventController::createEventApi
    methods: [POST]

######################################
############# RUTAS FOROS ############

# Ruta para la API de foros
api_forums:
    path: /api/forums
    controller: App\Controller\ForumController::getForums
    methods: [GET]

# Ruta para listar los foros (vista con Twig)
forums_list:
    path: /forums
    controller: App\Controller\ForumController::index
    methods: [GET]

# Ruta para la creación de foros
create_forum:
    path: /forums/new
    controller: App\Controller\ForumController::createForum
    methods: [POST]

# Ruta para eliminar un foro
delete_forum:
    path: /forums/{id}
    controller: App\Controller\ForumController::deleteForum
    methods: [DELETE]

# Ruta para añadir una respuesta a un foro específico
add_response:
    path: /forums/{id}/add-response
    controller: App\Controller\ForumController::addResponse
    methods: [GET, POST]

# Ruta para añadir una respuesta a un foro mediante POST
add_forum_response:
    path: /forums/{id}/response
    controller: App\Controller\ForumController::addResponseToForum
    methods: [POST]

# Ruta para obtener todas las respuestas de un foro específico
forum_responses:
    path: /api/forums/{id}/responses
    controller: App\Controller\ForumController::getResponses
    methods: [GET]

# Ruta para añadir una sub-respuesta a una respuesta específica en un foro
add_sub_response:
    path: /forums/{forumId}/response/{responseId}/subresponse
    controller: App\Controller\ForumController::addSubResponse
    methods: [POST]


######################################
############# RUTAS LOGIN ############

# Ruta para login usando JWT
login:
    path: /api/login
    controller: lexik_jwt_authentication.controller.login
    methods: [POST]

# Ruta para registrar usuarios
register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: [POST]

# Ruta para listar usuarios
users_list:
    path: /users
    controller: App\Controller\UserController::index
    methods: [GET]

# Ruta para obtener el perfil del usuario autenticado
get_profile:
    path: /api/profile
    controller: App\Controller\ProfileController::getProfile
    methods: [GET]

# Ruta para crear o actualizar el perfil del usuario autenticado
save_profile:
    path: /api/profile
    controller: App\Controller\ProfileController::saveProfile
    methods: [POST, PUT]

# Ruta para acceder a la carpeta de fotos subidas
uploads:
    path: /uploads/photos
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirect


######################################
############# RUTAS G_ROCK ###########

api_grupos_rock_list:
    path: /api/grupos-rock
    controller: App\Controller\GruposRockController::listGruposRock
    methods: GET

grupos_rock_get:
    path: /api/grupos-rock/{id}
    controller: App\Controller\GruposRockController::getGrupoRock
    methods: GET

# Ruta para crear o actualizar
grupos_rock_save:
    path: /api/grupos-rock
    controller: App\Controller\GruposRockController::saveGrupoRock
    methods: [POST, PUT]

delete_grupos_rock:
    path: /admin/grupos-rock/delete/{id}
    controller: App\Controller\GruposRockController::deleteGrupoRock
    methods: POST

edit_grupos_rock:
    path: /admin/grupos-rock/edit/{id}
    controller: App\Controller\GruposRockController::editGrupoRock
    methods: [GET, POST]

grupos_rock_create_form:
    path: /admin/grupos-rock/new
    controller: App\Controller\GruposRockController::createGrupoRock
    methods: [GET, POST]

list_grupos_rock:
    path: /grupos-rock
    controller: App\Controller\GruposRockController::listGruposRockView
    methods: GET

favicon:
    path: /favicon.ico
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirect
    defaults:
        path: /path/to/favicon.ico
        permanent: true