# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'  # Ruta a la clave privada
    public_key: '%kernel.project_dir%/config/jwt/public.pem'   # Ruta a la clave pública
    pass_phrase: '%env(JWT_PASSPHRASE)%'                       # Frase de paso para las claves
    token_ttl: 360000                                          # Tiempo de vida del token (en segundos)




